stages:
  - build
  - test
  - deploy

image: docker:26.1.4

services:
  - docker:26.1.4-dind

test-jmeter:
  stage: test
  before_script:
    - docker compose build
    - docker compose up -d
  script:
    - jmeter -n -t jmeter/testplan/TestPlan.jmx -l jmeter/results/result.jtl
  after_script:
    - docker compose down
  artifacts:
    untracked: false
    when: always
    access: all
    paths:
      - results/result.jtl
      - logs/log.log
  only:
      - main
      - develop
  tags:
      - dind

test-postman:
  stage: test
  before_script:
    # Installing Postman CLI
    - docker info
    - docker-compose --version
    - wget -O - "https://dl-cli.pstmn.io/install/linux64.sh" | sh
    - docker compose build
    - docker compose up -d
  script:
    # Login using your Postman API keys
    - postman login --with-api-key $POSTMAN_API_KEY
    - postman collection run "32069873-6161a362-b7df-4871-ae34-840197b818b5"
  after_script:
    - docker compose down
  only:
    - main
    - develop
  tags:
    - dind
