stages:
  - build
  - test
  - deploy

test-jmeter:
  image: 
    name: justb4/jmeter:latest
    entrypoint: ["/bin/sh"]
  stage: test
  services: 
    - docker:dind
  before_script:
    - docker compose build
    - docker compose up -d
  script:
    - jmeter -n -t jmeter/testplan/TestPlan.jmx -l jmeter/results/result.jtl
  after_script:
    - docker compose down
  artifacts:
    untracked: false
    when: always
    access: all
    paths:
      - results/result.jtl
      - logs/log.log
  only:
      - main
      - develop
  tags:
      - dind

automated-api-tests:
  stage: test
  image: cimg/base:2024.06

  services:
    - docker:dind

  before_script:
    # Installing Postman CLI
    - curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
    - docker compose build
    - docker compose up -d

  script:
    # Login using your Postman API keys
    - postman login --with-api-key $POSTMAN_API_KEY
    - postman collection run "32069873-6161a362-b7df-4871-ae34-840197b818b5"

  after_script:
    - docker compose down
