/*
 * PIM-SWKS SoSe2024 REST API
 * PIM-SWKS SoSe2024 REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Post;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PostsApi
 */
@Disabled
public class PostsApiTest {

    private final PostsApi api = new PostsApi();

    /**
     * Create a new post
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPostTest() throws ApiException {
        Post post = null;
        Post response = api.createPost(post);
        // TODO: test validations
    }

    /**
     * Delete a post by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePostByIdTest() throws ApiException {
        Long id = null;
        Post response = api.deletePostById(id);
        // TODO: test validations
    }

    /**
     * Returns a post by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPostByIdTest() throws ApiException {
        Long id = null;
        Post response = api.getPostById(id);
        // TODO: test validations
    }

    /**
     * Returns all posts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPostsTest() throws ApiException {
        List<Post> response = api.getPosts();
        // TODO: test validations
    }

    /**
     * Returns all posts authored by this user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPostsForUserTest() throws ApiException {
        Long id = null;
        List<Post> response = api.getPostsForUser(id);
        // TODO: test validations
    }

    /**
     * Update a post by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePostByIdTest() throws ApiException {
        Long id = null;
        Post post = null;
        Post response = api.updatePostById(id, post);
        // TODO: test validations
    }

}
