name: Automated API tests using Postman CLI

on: push

jobs:
    test-postman:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Postman CLI
              run: |
                  curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
            - name: Login to Postman CLI
              run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
            - name: Run API tests
              run: |
                  postman collection run "27514453-f372f232-93ad-4592-8bc8-564346ba8f3c"
                  # Lint your API using Postman CLI
                  postman api lint b7b7ccc8-57f5-41ee-b282-85889746455e
