name: Run API tests for ASP.NET
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  aspnet-test:
    name: Run ASP.NET tests
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rest-aspnet
    steps:
      - uses: actions/checkout@v4
      - name: Build ASP.NET project
        run: dotnet build
      - name: Test ASP.NET project
        run: dotnet test
  
  test_postman_aspnet:
    needs: aspnet-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Start docker containers
        run: docker compose up -d --build rest-aspnet mariadb
      - name: Run API tests
        run: postman collection run "32069873-6161a362-b7df-4871-ae34-840197b818b5"
      - name: Stop docker containers
        run: docker compose down
  
  test_jmeter_aspnet:
    needs: aspnet-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start docker containers
        run: docker compose up -d rest-aspnet mariadb
      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
          testFilePath: jmeter/TestPlan.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO -Jport=38080"

      - name: Stop docker containers
        run: docker compose down
      - uses: actions/upload-artifact@v4
        with:
          name: jmeter-test-results
          path: reports/
